# Generated by Django 2.0.5 on 2018-05-25 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='vc_codEstado',
            field=models.ForeignKey(db_column='vc_codEstado', on_delete=django.db.models.deletion.PROTECT, related_name='vc_codEstado_cli', to='mantenimiento.GeneralDetalle'),
        ),
    ]
